
<div id="head-band">
  <!--<div id="headTitle"><?PHP echo $this->title; ?></div>-->
  <div id="topShare"> 
    <!-- AddToAny BEGIN --> 
    <a class="a2a_dd" href="http://www.addtoany.com/share_save"><img src="http://static.addtoany.com/buttons/share_save_120_16.gif" width="120" height="16" border="0" alt="Share"/></a> 
    <script type="text/javascript" src="http://static.addtoany.com/menu/page.js"></script> 
    <!-- AddToAny END --> 
  </div>
</div>
<div id="misc-box">
  <div class="content-box"><?PHP echo $this->copy_text; ?></div>
</div>
