  <div class="contentWrap" id="contentWrap<?PHP echo $this->id; ?>">
    <div id="copyBlock">
      <h2>Sitemap</h2>
      <div id="searchBox">
        <div class="searchResults">
          <?php if(count($this->pages) > 0): ?>
          <h1>Pages</h1>
          <?php foreach($this->pages AS $key => $row): ?>
          <div class="srchRslt"> <?PHP echo '<a href="'.$row[pglink].'" title="'.$row[title].'">'.$row[title].'</a>'; ?> </div>
          <?php endforeach; ?>
          <?php else: ?>
          <?php endif; ?>
          <?php if(count($this->news) > 0): ?>
          <h1>News</h1>
          <?php foreach($this->news AS $key => $row): ?>
          <div class="srchRslt">
			<?PHP
            // grab dynamic route if assigned
            $routes = new Application_Model_Routes;
            $routesMapper = new Application_Model_RoutesMapper;
            if($row[route_id]){
                $routesMapper->find($row[route_id],$routes);
                if($routes->getUri()){
                    $lnkFnl = '/'.$routes->getUri().'/';
                } else {
                    $lnkFnl = '/news/item/'.$this->cleanDups(strtolower(preg_replace("/[^A-Za-z0-9\s\s+]/","-",$row[name]))).'/'.$row[id].'/';
                }
            } else {
                $lnkFnl = '/news/item/'.$this->cleanDups(strtolower(preg_replace("/[^A-Za-z0-9\s\s+]/","-",$row[name]))).'/'.$row[id].'/';
            }
            ?>
            <?PHP $pgLnk = $lnkFnl;
				  echo '<a href="'.$pgLnk.'" title="'.$row[title].'">'.$row[name].'</a>'; ?>
          </div>
          <?php endforeach; ?>
          <?php else: ?>
          <?php endif; ?>
          <?php if(count($this->events) > 0): ?>
          <h1>Events</h1>
          <?php foreach($this->events AS $key => $row): ?>
          <div class="srchRslt">
			<?PHP
            // grab dynamic route if assigned
            $routes = new Application_Model_Routes;
            $routesMapper = new Application_Model_RoutesMapper;
            if($row[route_id]){
                $routesMapper->find($row[route_id],$routes);
                if($routes->getUri()){
                    $lnkFnl = '/'.$routes->getUri().'/';
                } else {
                    $lnkFnl = '/event/name/'.$this->cleanDups(strtolower(preg_replace("/[^A-Za-z0-9\s\s+]/","-",$row[name]))).'/'.$row[id].'/';
                }
            } else {
                $lnkFnl = '/event/name/'.$this->cleanDups(strtolower(preg_replace("/[^A-Za-z0-9\s\s+]/","-",$row[name]))).'/'.$row[id].'/';
            }
            ?>
            <?PHP $pgLnk = $lnkFnl;
			  echo '<a href="'.$pgLnk.'" title="'.$row[title].'">'.$row[name].'</a>'; ?>
          </div>
          <?php endforeach; ?>
          <?php else: ?>
          <?php endif; ?>
          <?php if(count($this->press_releases) > 0): ?>
          <h1>Press Releases</h1>
          <?php foreach($this->press_releases AS $key => $row): ?>
          <div class="srchRslt">
            <?PHP 

		if($row[filelnk] != ''){
			$pgLnk = str_replace(' ','+',$row[filelnk]);
		} else {
			$pgLnk = '/press-releases/item/'.strtolower(preg_replace("/[^A-Za-z0-9\s\s+]/","-",$row[title])).'/'.$row[id].'/';
		}

	  echo '<a href="'.$pgLnk.'" title="'.$row[title].'">'.date("n/j/Y",strtotime($row[date])).' - '.$row[title].'</a>'; ?>
          </div>
          <?php endforeach; ?>
          <?php else: ?>
          <?php endif; ?>
          <?php if(count($this->partners) > 0): ?>
          <h1>Partners</h1>
          <?php foreach($this->partners AS $key => $row): ?>
          <div class="srchRslt">
            <?PHP 

		if($row[link] != ''){
			$pgLnk = str_replace(' ','+',$row[link]);
		} else {
			$pgLnk = 'http://www.ynotpizza.com/partners/partner/'.strtolower(preg_replace("/[^A-Za-z0-9\s\s+]/","-",$row[name])).'/'.$row[id].'/';
		}

	  echo '<a href="'.$pgLnk.'" title="'.$row[name].'">'.$row[name].'</a>'; ?>
          </div>
          <?php endforeach; ?>
          <?php else: ?>
          <?php endif; ?>
          <?php if(count($this->reference_materials) > 0): ?>
          <h1>Reference Materials</h1>
          <?php foreach($this->reference_materials AS $key => $row): ?>
          <div class="srchRslt">
            <?PHP 
		if($row[filelnk] != ''){
			$pgLnk = str_replace(' ','+',$row[filelnk]);
		} else {
			$pgLnk = 'http://www.ynotpizza.com/reference-materials/item/'.strtolower(preg_replace("/[^A-Za-z0-9\s\s+]/","-",$row[name])).'/'.$row[id].'/';
		}

	  echo '<a href="'.$pgLnk.'" title="'.$row[name].'">'.$row[name].'</a>'; ?>
          </div>
          <?php endforeach; ?>
          <?php else: ?>
          <?php endif; ?>
        </div>
      </div>
    </div>
  </div>
  <div class="clear"></div>
