<div id="adminLeftClm">
  <?php if(count($this->paginator) > 0): ?>
  <form method="post" name="videos">
    <table class="adminListing">
      <tr>
        <th>Name</th>
        <th>Modified</th>
        <th>Preview</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <?php foreach($this->paginator AS $key => $row): ?>
      <?PHP

	  // create video sting
	  if($row->local != ''){
		  $vidPrecLnk = '<a title="'.$row->name.'" class="videoPrev" href="/jwplayer/player.swf?file=/upload/video/'.urlencode($row->local).'&amp;autostart=1"><img src="/images/admin/mag.png" alt="preview" /></a>';
	  } elseif($row->remote != '') {
		  $vidPrecLnk = '<a title="'.$row->name.'" class="videoPrev" href="/jwplayer/player.swf?file='.urlencode($row->remote).'&amp;autostart=1"><img src="/images/admin/mag.png" alt="preview" /></a>';
	  } else {
		  $vidPrecLnk = '';
	  }
	  ?>
      <tr>
        <td><?=$row->name?></td>
        <td><?=date("F j, Y, g:i a",strtotime($row->modified))?></td>
        <td align="center"><?PHP echo $vidPrecLnk; ?></td>
        <td align="center"><a href="/admin_videos/edit/?id=<?=$row->id?>"><img src="/images/admin/pencil.png" alt="edit" /></a></td>
        <td align="center"><input type="checkbox" name="delete[]" value="<?=$row->id?>" /></td>
      </tr>
      <?php endforeach; ?>
      <tr>
        <td colspan="5" align="right"><?php echo $this->paginator; ?></td>
      </tr>
      <tr>
        <td colspan="5" align="right"><input name="apply" type="image" src="/images/buttons/apply.png" /></td>
      </tr>
    </table>
  </form>
  <?php else: ?>
  No results.
  <?php endif; ?>
</div>
<div id="adminRightClm"> <a href="/admin_videos/edit/"><img src="/images/buttons/button1up.png" alt="button 1" /></a> </div>
