<script src="/lib/ckeditor/ckeditor.js" type="text/javascript"></script>
<script type="text/javascript">
$(function(){
	var filemanager = '/lib/ckeditor/filemanager/';
	var browser = filemanager + 'browser/default/browser.html';
	var connector = filemanager + 'connectors/php/connector.php';
	var upload = filemanager + 'connectors/php/upload.php';
	if($('#copy_text').length) {
	  CKEDITOR.replace( 'copy_text',
	  {    
		customConfig : this.config,
		width:"750",
		filebrowserBrowseUrl : browser +'?Connector=' + connector,
		filebrowserImageBrowseUrl : browser + '?Type=Image&Connector=' + connector,
		filebrowserFlashBrowseUrl : browser + '?Type=Flash&Connector=' + connector,
		filebrowserUploadUrl : upload + '?type=Files',
		filebrowserImageUploadUrl : upload + '?type=Images',
		filebrowserFlashUploadUrl : upload + '?type=Flash'
	  });
	}
	if($('#mobile_text').length) {
	  CKEDITOR.replace( 'mobile_text',
	  {    
		customConfig : this.config,
		width:"750",
		filebrowserBrowseUrl : browser +'?Connector=' + connector,
		filebrowserImageBrowseUrl : browser + '?Type=Image&Connector=' + connector,
		filebrowserFlashBrowseUrl : browser + '?Type=Flash&Connector=' + connector,
		filebrowserUploadUrl : upload + '?type=Files',
		filebrowserImageUploadUrl : upload + '?type=Images',
		filebrowserFlashUploadUrl : upload + '?type=Flash'
	  });
	}
	if($('#seo_text').length) {
	  CKEDITOR.replace( 'seo_text',
	  {    
		customConfig : this.config,
		width:"750",
		filebrowserBrowseUrl : browser +'?Connector=' + connector,
		filebrowserImageBrowseUrl : browser + '?Type=Image&Connector=' + connector,
		filebrowserFlashBrowseUrl : browser + '?Type=Flash&Connector=' + connector,
		filebrowserUploadUrl : upload + '?type=Files',
		filebrowserImageUploadUrl : upload + '?type=Images',
		filebrowserFlashUploadUrl : upload + '?type=Flash'
	  });
	}
});

$(function() {

	$( "#tabs" ).tabs();
});
</script>
<style type="text/css">
#linkIndicate {
	float:left;
	width:18px;
	height:18px;
	margin-top:5px;
	margin-left:5px;
}
</style>

<div id="adminLeftClm">
  <form id="inventEdit" enctype="multipart/form-data" method="post">
    <div id="tabs" style="width:742px">
      <ul>
        <li><a href="#tabs-1">Settings</a></li>
        <li><a href="#tabs-2">Options</a></li>
        <li><a href="#tabs-3">Media</a></li>
        <li><a href="#tabs-4">SEO</a></li>
      </ul>
      <div id="tabs-1">
        <dl class="zend_form">
          <dt id="title-label">
            <label for="title" class="required">Title:</label>
          </dt>
          <dd id="title-element">
            <input type="text" name="title" id="title" value="<?PHP echo $this->pages['title']; ?>" size="80" />
            <ul class="errors">
              <li>Value is required and can't be empty</li>
            </ul>
          </dd>
          <dt id="parent_id-label">
            <label for="parent_id" class="optional">Parent Page:</label>
          </dt>
          <dd id="parent_id-element">
            <select name="parent_id" id="parent_id">
              <?PHP
				foreach($this->pagesdd as $id => $item){
					echo '<option value="'.$id.'" label="'.$item.'"'.($id == $this->pages['parent_id'] ? ' selected="selected" ' : '').'>'.$item.'</option>';
				}
				?>
            </select>
          </dd>
          <dt id="pgsort-label">
            <label for="pgsort" class="required">Sort Order:</label>
          </dt>
          <dd id="pgsort-element">
            <input type="text" name="pgsort" id="pgsort" value="<?PHP echo ($this->pages['pgsort'] > 0 ? $this->pages['pgsort'] : 0); ?>" size="10" />
            <ul class="errors">
              <li>Value is required and can't be empty</li>
            </ul>
          </dd>
          <dt id="copy_text-label">
            <label for="copy_text" class="required">Page Copy:</label>
          </dt>
          <dd id="copy_text-element">
            <textarea name="copy_text" id="copy_text" rows="10" columns="20" cols="80"><?PHP echo str_replace('</textarea>', htmlentities('</textarea>'),$this->pages['copy_text']); ?></textarea>
          </dd>
          <dt id="copy_text-label">
            <label for="mobile_text" class="required">Mobile Copy:</label>
          </dt>
          <dd id="copy_text-element">
            <textarea name="mobile_text" id="mobile_text" rows="10" columns="20" cols="80"><?PHP echo str_replace('</textarea>', htmlentities('</textarea>'),$this->pages['mobile_text']); ?></textarea>
          </dd>
        </dl>
      </div>
      <div id="tabs-2">
        <dl class="zend_form">
          <dt id="calendar-label">
            <label for="calendar" class="optional">Display Calendar:</label>
          </dt>
          <dd id="calendar-element">
            <input type="checkbox" name="calendar" id="calendar" value="1"<?PHP echo ($this->pages['calendar'] == 1 ? ' checked="checked" ' : ''); ?>/>
          </dd>
          <dt id="menu-label">
            <label for="menu" class="optional">Do not display in menu:</label>
          </dt>
          <dd id="menu-element">
            <input type="checkbox" name="menu" id="menu" value="1"<?PHP echo ($this->pages['menu'] == 1 ? ' checked="checked" ' : ''); ?>/>
          </dd>
          <dt id="new_window-label">
            <label for="new_window" class="optional">Open Link in New Window:</label>
          </dt>
          <dd id="new_window-element">
            <input type="checkbox" name="new_window" id="new_window" value="1"<?PHP echo ($this->pages['new_window'] == 1 ? ' checked="checked" ' : ''); ?>/>
          </dd>
          <dt id="docLnk-label">
            <label for="docLnk" class="optional">Form:</label>
          </dt>
          <dd id="docLnk-element">
            <select name="form_id" id="form_id">
              <option value="0"></option>
              <?PHP
				foreach($this->forms as $item){
					echo '<option value="'.$item->id.'"'.($item->id == $this->pages['form_id'] ? ' selected="selected" ' : '').'>'.$item->name.'</option>';
				}
				?>
            </select>
          </dd>
          <dt id="docLnk-label">
            <label for="docLnk" class="optional">Link Document: (Populates File Link on selection.)</label>
          </dt>
          <dd id="docLnk-element">
            <select name="docLnk" id="docLnk">
              <option value="0"></option>
              <?PHP
				foreach($this->docs as $item){
					echo '<option value="'.$item[filename].'">'.$item[filename].'</option>';
				}
				?>
            </select>
          </dd>
          <dt id="filelnk-label">
            <label for="filelnk" class="optional">External or File Link: (Link to another file or site.)</label>
          </dt>
          <dd id="filelnk-element">
            <input type="text" name="filelnk" id="filelnk" value="<?PHP echo $this->pages['filelnk']; ?>" size="80" />
          </dd>
        </dl>
      </div>
      <div id="tabs-3">
        <dl class="zend_form">
          <dt id="playlist-label">
            <label for="playlist" class="optional">Playlist:</label>
          </dt>
          <dd id="playlist-element">
            <select name="playlist" id="playlist">
              <option value=""></option>
              <?PHP
				foreach($this->playlists as $item){
					echo '<option value="'.$item->id.'"'.($item->id == $this->pages['playlist'] ? ' selected="selected" ' : '').'>'.$item->name.'</option>';
				}
				?>
            </select>
          </dd>
          <dt id="slideshow-label">
            <label for="slideshow" class="optional">Slideshow:</label>
          </dt>
          <dd id="slideshow-element">
            <select name="slideshow" id="slideshow">
              <option value=""></option>
              <?PHP
				foreach($this->slideshows as $item){
					echo '<option value="'.$item->id.'"'.($item->id == $this->pages['slideshow'] ? ' selected="selected" ' : '').'>'.$item->name.'</option>';
				}
				?>
            </select>
          </dd>
        </dl>
      </div>
      <div id="tabs-4">
        <dl class="zend_form">
          <dt id="title_tag-label">
            <label for="link_name" class="required">Link Name:</label>
          </dt>
          <dd id="title_tag-element">
            <input style="float:left" type="text" name="link_name" id="link_name" value="<?PHP echo $this->pages['link_name']; ?>" size="80" />
            <div class="ui-icon" id="linkIndicate"></div>
            <div style="clear:both"></div>
          </dd>
          <dt id="title_tag-label">
            <label for="title_tag" class="required">Header Title:</label>
          </dt>
          <dd id="title_tag-element">
            <input type="text" name="title_tag" id="title_tag" value="<?PHP echo $this->pages['title_tag']; ?>" size="80" />
          </dd>
          <dt id="desc_tag-label">
            <label for="desc_tag" class="optional">Meta Description:</label>
          </dt>
          <dd id="desc_tag-element">
            <textarea name="desc_tag" id="desc_tag" rows="5" columns="20" cols="80"><?PHP echo $this->pages['desc_tag']; ?></textarea>
          </dd>
          <dt id="keyword_tag-label">
            <label for="keyword_tag" class="optional">Meta Keyword:</label>
          </dt>
          <dd id="keyword_tag-element">
            <textarea name="keyword_tag" id="keyword_tag" rows="5" columns="20" cols="80"><?PHP echo $this->pages['keyword_tag']; ?></textarea>
          </dd>
        </dl>
      </div>
    </div>
    <dl class="zend_form">
      <dt id="id-label">&#160;</dt>
      <dd id="id-element">
        <input type="hidden" name="id" value="<?PHP echo $this->pages['id']; ?>" id="id" />
        <input type="hidden" name="route_id" value="<?PHP echo $this->pages['route_id']; ?>" id="route_id" />
      </dd>
      <dt id="apply-label">&#160;</dt>
      <dd>
        <input type="image" name="apply" id="apply" src="/images/buttons/apply.png" alt="" />
      </dd>
    </dl>
  </form>
</div>
<div id="adminRightClm"> <a href="/admin_pages/"><img src="/images/buttons/listing.png" alt="button 1" /></a> <a href="/admin_pages/edit/"><img src="/images/buttons/button1up.png" alt="button 2" /></a> </div>
