<div id="adminLeftClm">
  <?php if(count($this->paginator) > 0): ?>
  <form method="post" name="videos">
    <table class="adminListing">
      <tr>
        <th>Filename</th>
        <th>Modified</th>
        <th>Preview</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <?php foreach($this->paginator AS $key => $row): ?>
      <?PHP
	  // create video sting
		  $vidPrecLnk = '<a title="'.$row->filename.'" target="_blank" href="/upload/docs/'.$row->filename.'"><img src="/images/admin/mag.png" alt="preview" /></a>';
	  ?>
      <tr>
        <td><?=$row->filename?></td>
        <td><?=date("F j, Y, g:i a",strtotime($row->modified))?></td>
        <td align="center"><?PHP echo $vidPrecLnk; ?></td>
        <td align="center"><a href="/admin_videos/edit/?id=<?=$row->id?>"><img src="/images/admin/pencil.png" alt="edit" /></a></td>
        <td align="center"><input type="checkbox" name="delete[]" value="<?=$row->id?>" /></td>
      </tr>
      <?php endforeach; ?>
      <tr>
        <td colspan="5" align="right"><?php echo $this->paginator; ?></td>
      </tr>
      <tr>
        <td colspan="5" align="right"><input name="apply" type="image" src="/images/buttons/apply.png" /></td>
      </tr>
    </table>
  </form>
  <?php else: ?>
  No results.
  <?php endif; ?>
</div>
<div id="adminRightClm"> <a href="/admin_documents/edit/"><img src="/images/buttons/button1up.png" alt="button 1" /></a> </div>
