<div id="adminLeftClm">
  <?PHP
if($this->page != ''){
	$pageStart = ($this->page-1)*10;
}
$counter = $pageStart;
?>
  <?php if(count($this->paginator) > 0): ?>
  <form method="post" name="formSubs">
    <table class="adminListing">
      <tr>
        <th>#</th>
        <th>Date</th>
        <th>Type</th>
        <th>View</th>
        <th>Delete</th>
      </tr>
      <?php foreach($this->paginator AS $key => $row): ?>
      <?PHP

	  $counter++;

	  ?>
      <tr>
        <td><?=$counter?></td>
        <td><?=date("F j, Y, g:i a",strtotime($row[date]))?></td>
        <td><?=$row[type]?></td>
        <td align="center"><a href="/admin_forms/submissions-view/?id=<?=$row[id]?>"><img src="/images/admin/pencil.png" alt="edit" /></a></td>
        <td align="center"><input type="checkbox" name="delete[]" value="<?=$row[id]?>" /></td>
      </tr>
      <?php endforeach; ?>
      <tr>
        <td colspan="5" align="right"><?php echo $this->paginator; ?></td>
      </tr>
      <tr>
        <td colspan="9" align="right"><input name="apply" type="image" src="/images/buttons/apply.png" /></td>
      </tr>
    </table>
  </form>
  <?php else: ?>
  No results.
  <?php endif; ?>
</div>
<div id="adminRightClm"> <a href="/admin_forms/reports/">Reports</a> </div>
