<div id="inventoryBox">
  <div id="inventoryLeft">
    <div id="inventoryLeftPad">
      <p class="invSrchTitle">SELECT FROM<br />
        INVENTORY</p>
      <div id="invSrchFrm">
        <form method="get" name="invSrch" action="/inventory/">
          <label>Model Year</label>
          <select id="from" name="from">
            <?php echo $this->fromOpts; ?>
          </select>
          -
          <select id="to" name="to">
            <?php echo $this->toOpts; ?>
          </select>
          <div class="fillBlocks">
            <label>Vehicle Body Style</label>
            <select id="style" name="style">
              <option>All</option>
              <?PHP echo $this->styleOpts; ?>
            </select>
            <label>Vehicle Make</label>
            <select id="make" name="make">
              <option>All</option>
              <?PHP echo $this->makeOpts; ?>
            </select>
            <label>Vehicle Model</label>
            <select id="model" name="model">
              <option>All</option>
              <?PHP echo $this->modelOpts; ?>
            </select>
            <label>Vehicle Color</label>
            <select id="color" name="color">
              <option>All</option>
              <?PHP echo $this->colorOpts; ?>
            </select>
            <div id="invButWrap">
              <input type="reset" value="Reset" id="reset" name="reset" />
              <input type="submit" value="Search" id="submit" name="submit" />
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div id="inventoryResults">
    <?php if(count($this->paginator) > 0): ?>
    <?php echo $this->paginator; ?>
    <div class="clear"></div>
    <?php foreach($this->paginator AS $key => $row): ?>
    <?PHP

  $imagesArr = explode(';',$row[images]);

  echo '<div class="invRes" onclick="location.href=\'/inventory/vehicle/stocknum/'.$row[stockNum].'\'">
  		<div class="invResImg">'.(count($imagesArr) > 0 ? $this->image($imagesArr[0],'/application/upload/invent/images/'.$imagesArr[0],array(),'100x100') : '&nbsp;').'</div>
  		<div class="invResInfo">'.$row[year].'</div>
  		<div class="invResInfo">'.$row[make].'</div>
  		<div class="invResInfo">'.$row[model].'</div>
  		<div class="invResInfo">'.$row[style].'</div>
  		<div class="invResInfo">'.$row[color].'</div>
		<div class="clear"></div></div>';

  ?>
    <?php endforeach; ?>
    <?php echo $this->paginator; ?>
    <div class="clear"></div>
    <?php else: ?>
    No results.
    <?php endif; ?>
  </div>
</div>
<div id="tabsWrap">
  <div id="tabs"> <img src="/images/tabs.png" alt="our process tabs" name="tabRow" width="566" height="48" border="0" usemap="#tabRowMap" id="tabRow" />
    <map name="tabRowMap" id="tabRowMap">
      <area shape="rect" coords="15,4,319,36" href="javascript: void(0);" onclick="switchTab(1)" />
      <area shape="rect" coords="328,4,401,40" href="javascript: void(0);" onclick="switchTab(2)" />
      <area shape="rect" coords="406,2,481,38" href="javascript: void(0);" onclick="switchTab(3)" />
      <area shape="rect" coords="485,-1,565,40" href="javascript: void(0);" onclick="switchTab(4)" />
    </map>
    <img style="display:block" src="/images/tab1.png" alt="info tab one" name="tab1" width="991" height="150" id="tab1" class="tabs" /> <img src="/images/tab2.png" alt="info tab one" name="tab1" width="485" height="146" id="tab2" class="tabs" /> <img src="/images/tab3.png" alt="info tab one" name="tab1" width="524" height="146" id="tab3" class="tabs" /> <img src="/images/tab4.png" alt="info tab one" name="tab1" width="453" height="146" id="tab4" class="tabs" /></div>
</div>
<p><img height="505" width="1024" alt="mid background image" src="/images/inventorybg.png" id="testbgimage" /></p>
<?PHP 

echo $this->videoOP;

?>
