<div id="breadCrumbs"><a href="/">HOME</a> &raquo; <a href="/reference-materials/">Reference Materials</a> &raquo; <?PHP echo $this->bc; ?></div>
<div id="referencePage">
  <h1 id="referenceTitle"><?PHP echo $this->title; ?></h1>
  <img id="referenceImage" src="/upload/reference/<?PHP echo $this->image; ?>" alt="<?PHP echo $this->title; ?>" />
  <div id="referenceCopy">
    <?PHP 
echo $this->copy_text; 
?>
  </div>
</div>
