<?php if ($this->pageCount): ?>

<div class="paginationControl"> 
  
  <!-- Previous page link -->
  
  <?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>?sid=<?PHP echo $_GET['sid']; ?>"> &lt; Previous </a> |
  <?php else: ?>
  <span class="disabled">&lt; Previous</span> |
  <?php endif; ?>
  
  <!-- Numbered page links -->
  
  <?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
  <a href="<?php echo $this->url(array('page' => $page)); ?>?sid=<?PHP echo $_GET['sid']; ?>"> <?php echo $page; ?> </a> |
  <?php else: ?>
  <span id="current_page"><?php echo $page; ?></span> |
  <?php endif; ?>
  <?php endforeach; ?>
  
  <!-- Next page link -->
  
  <?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>?sid=<?PHP echo $_GET['sid']; ?>"> Next &gt; </a>
  <?php else: ?>
  <span class="disabled">Next &gt;</span>
  <?php endif; ?>
</div>
<?php endif; ?>
